# Atelier Scikit-learn

## Partie 0 – mise en place de l’environnement

### Installer et importer seaborn, matplotlib et pandas

In [2]:
import seaborn as sns
import pandas as pd
import matplotlib as plt

print("Seaborn version :", sns.__version__)
print("Pandas version  :", pd.__version__)
print("matplotlib version  :", plt.__version__)

Seaborn version : 0.13.2
Pandas version  : 3.0.5
matplotlib version  : 3.11.1

### Importer mesures_capteurs.csv dans le dataframe df

In [3]:
df =pd.read_csv("data/mesures_capteurs.csv")

### Explorer le dataframe df

In [4]:
print("Premières lignes :")
display(df.head())
print("\nDimensions :", df.shape)

Premières lignes :

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

Dimensions : (605, 9)

## Partie 1 – Gestion des doublons 
## Avec Pandas, 
### 1) vérifier l’existence de doublons dans df

In [5]:
doublons= df.duplicated().sum()
print(f"le dataframe compte {doublons} doublons")

le dataframe compte 5 doublons

### 2) le cas échéant, supprimer les doublons puis vérifier la suppression

In [6]:
import pandas as pd
#affichage avant suppression des doublons
doublons= df.duplicated().sum()
print("Avant suppression des doublons")
print(f"le dataframe compte {doublons} doublons")
#suppression des doublons 
df=df.drop_duplicates()
doublons= df.duplicated().sum()
print("Apres suppression des doublons")
print(f"le dataframe compte {doublons} doublons")

Avant suppression des doublons
le dataframe compte 5 doublons
Apres suppression des doublons
le dataframe compte 0 doublons

## Partie 2 – Sélection de y (cible) et X (caractéristiques) 
### 1) Définir "etat" comme la cible ou valeur à prédire et "temperature", "humidite", "pression" et "consommation" comme caractéristiques ou variables explicatives

In [8]:
# Vérification des valeurs manquantes dans la colonne cible 'etat'
nan_etat = df['etat'].isnull().sum()
print(f"Nombre de valeurs manquantes dans la variable cible 'etat' : {nan_etat}")

# Suppression des lignes où la variable cible 'etat' est manquante
if nan_etat > 0:
    df = df.dropna(subset=['etat'])
    print("Lignes avec variable cible manquante supprimées !")

print(f"Dimensions du DataFrame df après nettoyage : {df.shape[0]} lignes.")

#  Définir 'etat' comme la cible ou valeur à prédire et 'temperature', 'humidite', 'pression' et 'consommation' comme caractéristiques
X = df[["temperature", "humidite", "pression", "consommation"]]
y = df["etat"]

Nombre de valeurs manquantes dans la variable cible 'etat' : 0
Dimensions du DataFrame df après nettoyage : 596 lignes.

### 2) Afficher les cinq premières lignes de X et de y

In [9]:
print("--- 5 premières lignes de X (Caractéristiques ou variables explicatives) ---")
display(X.head())
print("\n--- 5 premières lignes de y (Variable cible ou étiquette) ---")
display(y.head())

--- 5 premières lignes de X (Caractéristiques ou variables explicatives) ---

   temperature  humidite  pression  consommation
0        25.46     58.06   1008.95        287.28
1        24.00     79.73    993.39        116.20
2        25.82     54.47   1010.32        288.50
3        28.23     69.39   1019.62        136.65
4        20.58     53.80   1016.58        182.62

--- 5 premières lignes de y (Variable cible ou étiquette) ---

0    OK
1    OK
2    OK
3    OK
4    OK
Name: etat, dtype: str